### PR TITLE
Added dependencies-fix instruction

### PR DESCRIPTION
**Pull request by henri123lemoine**

### CODE REVIEW

**Comment by henri123lemoine** [comment]
@budzianowski

**Comment by budzianowski** [comment]
Please update https://github.com/kscalelabs/sim/blob/master/sim/requirements.txt

**Comment by jingxiangmo** [comment]
lgtm

**Comment by jingxiangmo** [comment]
@henri123lemoine, checks failed

**Comment by budzianowski** [comment]
@WT-MM - can you push it through

**Review by budzianowski — APPROVED** [review]

**Pull request merged**
